#include <t8_cmesh/t8_cmesh.h>
#include <t8_cmesh/t8_cmesh.hxx>
#include <t8_cmesh/t8_cmesh_examples.h>
#include <t8_cmesh/t8_cmesh_internal/t8_cmesh_tree_reindex.hxx>
#include <t8_vtk/t8_vtk_writer.h>

#include <gtest/gtest.h>

#include <array>
#include <map>
#include <set>

struct t8_test_cmesh_tree_reindex: public testing::Test
{
 protected:
  static constexpr t8_gloidx_t num_trees = 6;
  static constexpr int num_vertices = 4;
  static constexpr int num_coords = 3 * num_vertices;
  static constexpr int num_tet_faces = 4;

  using vertex_array_t = std::array<double, num_coords>;

  void
  SetUp () override
  {
    t8_cmesh_init (&cmesh);
    ASSERT_NE (cmesh, nullptr);

    /*
     * The reindex_trees flag is initialized to 1 by default.
     * Therefore, the test cmesh will be reindexed automatically during commit.
     */
    if (!cmesh->reindex_trees) {
      t8_cmesh_enable_tree_reordering (cmesh);
    }
    ASSERT_EQ (cmesh->reindex_trees, 1);

    t8_cmesh_init (&control_cmesh);
    ASSERT_NE (control_cmesh, nullptr);

    /*
     * The control mesh uses the same hypercube example, but disables reindexing.
     * It is used as the reference mesh with the original tree order.
     */
    control_cmesh->reindex_trees = 0;
  }

  void
  TearDown () override
  {
    if (cmesh != nullptr) {
      t8_cmesh_unref (&cmesh);
      cmesh = nullptr;
    }

    if (control_cmesh != nullptr) {
      t8_cmesh_unref (&control_cmesh);
      control_cmesh = nullptr;
    }
  }

  static vertex_array_t
  get_tree_vertices (t8_cmesh_t cmesh, const t8_locidx_t local_tree_id)
  {
    vertex_array_t vertices {};

    double *tree_vertices = t8_cmesh_get_tree_vertices (cmesh, local_tree_id);
    T8_ASSERT (tree_vertices != nullptr);

    for (int icoord = 0; icoord < num_coords; ++icoord) {
      vertices[icoord] = tree_vertices[icoord];
    }

    return vertices;
  }

  t8_cmesh_t cmesh = nullptr;
  t8_cmesh_t control_cmesh = nullptr;
};

TEST_F (t8_test_cmesh_tree_reindex, hypercube_commit_reindexes_trees_successfully_and_correctly)
{
  t8_productionf ("Test started\n");

  /*
   * Construct the control cmesh from the existing t8code hypercube example.
   * Reindexing was disabled in SetUp(), so this mesh keeps the original tree
   * order generated by t8_cmesh_new_hypercube.
   */
  t8_cmesh_new_hypercube (&control_cmesh, T8_ECLASS_TET, sc_MPI_COMM_SELF, 0, 0, 0);

  ASSERT_TRUE (t8_cmesh_is_committed (control_cmesh));

  t8_cmesh_vtk_write_file (control_cmesh, "test_cmesh_tree_reindex_original");

  /*
   * Construct the actual test cmesh from the same hypercube example.
   * The reindex_trees flag is enabled by default, so the reindexing is executed
   * during the commit inside t8_cmesh_new_hypercube.
   */
  t8_cmesh_new_hypercube (&cmesh, T8_ECLASS_TET, sc_MPI_COMM_SELF, 0, 0, 0);

  ASSERT_TRUE (t8_cmesh_is_committed (cmesh));

  t8_cmesh_vtk_write_file (cmesh, "test_cmesh_tree_reindex_reindexed");

  /*
   * The tetrahedral hypercube consists of six tetrahedral trees.
   * Since the test uses MPI_COMM_SELF, all trees are local.
   */
  for (t8_gloidx_t tree_id = 0; tree_id < num_trees; ++tree_id) {
    EXPECT_GE (t8_cmesh_get_local_id (control_cmesh, tree_id), 0);
    EXPECT_GE (t8_cmesh_get_local_id (cmesh, tree_id), 0);
  }

  /*
   * Build a reference map from vertex coordinates to original tree ids.
   * Since reindexing must not change the geometry, each reindexed tree should
   * match exactly one tree of the control mesh.
   */
  std::map<vertex_array_t, t8_gloidx_t> vertices_to_old_tree_id;

  for (t8_gloidx_t old_tree_id = 0; old_tree_id < num_trees; ++old_tree_id) {
    const t8_locidx_t old_local_tree_id = t8_cmesh_get_local_id (control_cmesh, old_tree_id);

    ASSERT_GE (old_local_tree_id, 0);
    EXPECT_EQ (t8_cmesh_get_global_id (control_cmesh, old_local_tree_id), old_tree_id);
    EXPECT_EQ (t8_cmesh_get_tree_class (control_cmesh, old_local_tree_id), T8_ECLASS_TET);

    const vertex_array_t vertices = get_tree_vertices (control_cmesh, old_local_tree_id);

    const auto inserted = vertices_to_old_tree_id.emplace (vertices, old_tree_id);
    ASSERT_TRUE (inserted.second) << "Duplicate vertex data in control cmesh for tree " << old_tree_id;
  }

  /*
   * Reconstruct the observed reindexing map from the committed reindexed cmesh.
   * If a tree in the reindexed cmesh has the same vertex coordinates as an old
   * tree in the control cmesh, then this old tree was mapped to the current new
   * tree id.
   */
  std::map<t8_gloidx_t, t8_gloidx_t> observed_reindex;
  std::set<t8_gloidx_t> old_tree_ids;
  std::set<t8_gloidx_t> new_tree_ids;

  bool reindex_is_identity = true;

  for (t8_gloidx_t new_tree_id = 0; new_tree_id < num_trees; ++new_tree_id) {
    const t8_locidx_t new_local_tree_id = t8_cmesh_get_local_id (cmesh, new_tree_id);

    ASSERT_GE (new_local_tree_id, 0);
    EXPECT_EQ (t8_cmesh_get_global_id (cmesh, new_local_tree_id), new_tree_id);
    EXPECT_EQ (t8_cmesh_get_tree_class (cmesh, new_local_tree_id), T8_ECLASS_TET);

    const vertex_array_t vertices = get_tree_vertices (cmesh, new_local_tree_id);

    const auto old_tree_entry = vertices_to_old_tree_id.find (vertices);

    ASSERT_NE (old_tree_entry, vertices_to_old_tree_id.end ())
      << "Could not find matching original tree for reindexed tree " << new_tree_id;

    const t8_gloidx_t old_tree_id = old_tree_entry->second;

    const auto inserted = observed_reindex.emplace (old_tree_id, new_tree_id);
    ASSERT_TRUE (inserted.second) << "Old tree " << old_tree_id << " was mapped more than once.";

    old_tree_ids.insert (old_tree_id);
    new_tree_ids.insert (new_tree_id);

    if (old_tree_id != new_tree_id) {
      reindex_is_identity = false;
    }

    t8_productionf ("Observed reindex: old global tree id %lli -> new global tree id %lli\n",
                    static_cast<long long> (old_tree_id), static_cast<long long> (new_tree_id));
  }

  /*
   * Check that the observed reindexing is a valid bijection.
   */
  EXPECT_EQ (observed_reindex.size (), static_cast<std::size_t> (num_trees));
  EXPECT_EQ (old_tree_ids.size (), static_cast<std::size_t> (num_trees));
  EXPECT_EQ (new_tree_ids.size (), static_cast<std::size_t> (num_trees));

  for (t8_gloidx_t tree_id = 0; tree_id < num_trees; ++tree_id) {
    EXPECT_EQ (old_tree_ids.count (tree_id), 1);
    EXPECT_EQ (new_tree_ids.count (tree_id), 1);
  }

  t8_productionf ("Reindexing is %s\n", reindex_is_identity ? "identity" : "non-identity");

  /*
   * Verify that all internal face joins were updated consistently.
   * The control cmesh gives the original connectivity. For each original join,
   * the old tree ids are mapped to their new tree ids and the same face
   * connection is queried in the reindexed cmesh.
   */
  for (t8_gloidx_t old_tree_id = 0; old_tree_id < num_trees; ++old_tree_id) {
    const t8_locidx_t old_local_tree_id = t8_cmesh_get_local_id (control_cmesh, old_tree_id);

    ASSERT_GE (old_local_tree_id, 0);

    for (int face = 0; face < num_tet_faces; ++face) {
      int old_dual_face = -1;
      int old_orientation = -1;

      const t8_locidx_t old_neighbor_local_tree_id
        = t8_cmesh_get_face_neighbor (control_cmesh, old_local_tree_id, face, &old_dual_face, &old_orientation);

      if (old_neighbor_local_tree_id < 0) {
        continue;
      }

      const t8_gloidx_t old_neighbor_tree_id = t8_cmesh_get_global_id (control_cmesh, old_neighbor_local_tree_id);

      /*
       * Check every undirected join only once.
       */
      if (old_tree_id > old_neighbor_tree_id) {
        continue;
      }

      const t8_gloidx_t new_tree_id = observed_reindex.at (old_tree_id);
      const t8_gloidx_t new_neighbor_tree_id = observed_reindex.at (old_neighbor_tree_id);

      const t8_locidx_t new_local_tree_id = t8_cmesh_get_local_id (cmesh, new_tree_id);
      const t8_locidx_t new_neighbor_local_tree_id = t8_cmesh_get_local_id (cmesh, new_neighbor_tree_id);

      ASSERT_GE (new_local_tree_id, 0);
      ASSERT_GE (new_neighbor_local_tree_id, 0);

      int new_dual_face = -1;
      int new_orientation = -1;

      const t8_locidx_t actual_neighbor_local_tree_id
        = t8_cmesh_get_face_neighbor (cmesh, new_local_tree_id, face, &new_dual_face, &new_orientation);

      ASSERT_GE (actual_neighbor_local_tree_id, 0);

      EXPECT_EQ (t8_cmesh_get_global_id (cmesh, actual_neighbor_local_tree_id), new_neighbor_tree_id);
      EXPECT_EQ (new_dual_face, old_dual_face);
      EXPECT_EQ (new_orientation, old_orientation);

      /*
       * Also verify the reverse direction of the join.
       */
      int reverse_dual_face = -1;
      int reverse_orientation = -1;

      const t8_locidx_t reverse_neighbor_local_tree_id = t8_cmesh_get_face_neighbor (
        cmesh, new_neighbor_local_tree_id, old_dual_face, &reverse_dual_face, &reverse_orientation);

      ASSERT_GE (reverse_neighbor_local_tree_id, 0);

      EXPECT_EQ (t8_cmesh_get_global_id (cmesh, reverse_neighbor_local_tree_id), new_tree_id);
      EXPECT_EQ (reverse_dual_face, face);

      t8_productionf ("Verified reindexed join old trees %lli-%lli -> new trees %lli-%lli\n",
                      static_cast<long long> (old_tree_id), static_cast<long long> (old_neighbor_tree_id),
                      static_cast<long long> (new_tree_id), static_cast<long long> (new_neighbor_tree_id));
    }
  }
}
