# Allow for minor coverage variations so that CI does not fail.
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.2%
    patch:
      default:
        target: auto
        threshold: 0.2%