#! /bin/bash

# This file is part of t8code.
# t8code is a C library to manage a collection (a forest) of multiple
# connected adaptive space-trees of general element classes in parallel.
#
# Copyright (C) 2015 the developers
#
# t8code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# t8code is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with t8code; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

TYPOS=`which typos 2> /dev/null`
if [ -z "$TYPOS" ]
then
  echo "ERROR: typos not found."
  echo "Please install typos."
  echo "See https://github.com/crate-ci/typos#install"
  exit 1
fi

repo_main_dir=`git rev-parse --show-toplevel`
(cd $repo_main_dir && typos)

echo "This script will correct all previously listed typos."
echo
read -p "Are you sure? ('Y' or 'y' to continue) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo Correcting all typos...
  (cd $repo_main_dir && typos -w)
  echo done.

  echo
  echo "Changed files according to git diff:"
  git diff --name-only
  echo
  echo "Should also all changed (according to git diff) files be indented?"
  read -p "('Y' or 'y' to continue) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo Indenting all files...
    changed_files=`git diff --name-only`
    (cd $repo_main_dir && ./scripts/t8indent $changed_files)
    echo done.
  else
    echo Aborted.
  fi
else
  echo Aborted.
fi